In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,3])

In [3]:
a

array([1, 2, 3, 4, 3])

In [4]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [5]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
c = np.zeros((4,5))

In [7]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
d = np.ones((3, 4))

In [9]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
e = np.arange(1, 8, 2)

In [11]:
e

array([1, 3, 5, 7])

In [14]:
e.dtype

dtype('int64')

In [15]:
f = np.eye(3)

In [16]:
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
g = np.linspace(1, 10, 2)

In [18]:
g

array([ 1., 10.])

In [19]:
#standard normal
h = np.random.randn(2)

In [20]:
h

array([-0.25999779, -1.22077607])

In [21]:
h = np.random.normal(10, 5, 10)

In [22]:
h

array([12.31749849,  0.87778849,  3.31731709, 11.90187404,  6.9965607 ,
       11.89813543, 16.0922546 , 11.29554191,  7.11619064,  7.12283064])

In [23]:
i = np.random.randint(1, 10, 4)

In [24]:
i

array([1, 7, 2, 2])

In [25]:
g + 3

array([ 4., 13.])

In [26]:
h * 4

array([49.26999396,  3.51115394, 13.26926835, 47.60749616, 27.98624279,
       47.59254172, 64.3690184 , 45.18216766, 28.46476257, 28.49132255])

In [28]:
i[2:]

array([2, 2])

In [29]:
i[:2]

array([1, 7])

In [30]:
i[:]

array([1, 7, 2, 2])

In [31]:
j = i.copy()

In [32]:
j

array([1, 7, 2, 2])

In [33]:
i is j

False

In [34]:
i == j

array([ True,  True,  True,  True])

In [39]:
k = np.random.normal(10, 4, (3, 3))

In [40]:
k[1]

array([ 8.15591959,  8.60070663, 11.86677779])

In [42]:
k[1][2]

11.866777789445099

In [43]:
k[1,2]

11.866777789445099

In [46]:
l = np.linspace(1, 10, 10)

In [47]:
l

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
l > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [49]:
l[l > 3]

array([ 4.,  5.,  6.,  7.,  8.,  9., 10.])

In [50]:
l.sum()

55.0

In [51]:
l.mean()

5.5

In [52]:
l.std()

2.8722813232690143

In [53]:
l.sum()

55.0

In [54]:
l.min()

1.0

In [55]:
l.max()

10.0

In [66]:
k.shape

(3, 3)

In [69]:
k.sum(axis=0)

array([23.85898409, 28.54498358, 32.48008791])

In [68]:
k.sum(axis=1)

array([31.18176019, 28.62340401, 25.07889139])

In [70]:
k

array([[ 8.00285926, 11.6460936 , 11.53280732],
       [ 8.15591959,  8.60070663, 11.86677779],
       [ 7.70020525,  8.29818334,  9.0805028 ]])

In [71]:
m = np.random.normal(3, 5, (3, 4))

In [72]:
m

array([[-5.65367537, 15.67411673,  5.64005386, -0.29900763],
       [-4.5646818 , -6.89666878,  4.56324856,  9.48107533],
       [-1.59189099,  6.14435965,  1.86369774, -1.16390867]])

In [73]:
m.sum(axis=0)

array([-11.81024817,  14.9218076 ,  12.06700016,   8.01815902])

In [74]:
m.sum(axis=1)

array([15.36148759,  2.5829733 ,  5.25225773])

In [77]:
o = np.arange(1,101).reshape(10, 10)

In [78]:
o

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [81]:
np.random.seed(101)
np.random.normal(4, 2, 4)

array([9.41369968, 5.25626542, 5.81593889, 5.00765151])

In [83]:
np.random.seed(101)
np.random.normal(4, 2, 4)

array([9.41369968, 5.25626542, 5.81593889, 5.00765151])